### ISSUE TITLE
I am unable to Import the solution into a Dynamics 365 instance

### ISSUE THREAD

**Issue by blueelvis** [carltoncolter/dyn-req-mgmt#1]
Hi,

I am following the below instructions -

1. Download the Package Deployer ZIP file which you have provided.
2. Copy paste the CRM package Deployer to it and try to Import the package using Powershell tools.

Powershell seems to hang up and I see that there is a reference to a solution file in `ImportConfig.xml` file as -
```
<configsolutionfile solutionpackagefilename="FedBizApps_RequestManagement.zip" publishworkflowsandactivateplugins="false"
                        overwriteunmanagedcustomizations="true" />
```
That file does not exist as well.

The RichTextBoxControl is getting deployed correctly but the solution is not deploying. Any idea what I might be missing?

Following is the log when I am trying to deploy using PowerShell commandlets -
```
PackageDeployer	Information	8	12-07-2018 01:15:44  Starting Config Reading process:
PackageDeployer	Information	8	12-07-2018 01:15:44  ReadingConfig from : E:\POCS\DYNAMICS\REQUESTMANAGEMENT-1.0\PkgFolder\ImportConfig.xml
PackageDeployer	Verbose	16	12-07-2018 01:15:44  Unpacking config
PackageDeployer	Information	8	12-07-2018 01:15:44  Reading Solutions.. Please wait
PackageDeployer	Information	8	12-07-2018 01:15:44  Found One Custom Extension
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	12-07-2018 01:15:44  Executed Command - WhoAmI : Execute (WhoAmI) request to CRM from IOrganizationService : duration: 00:00:00.1676879
PackageDeployer	Information	8	12-07-2018 01:15:44  Deployment Target Organization ID: 96045d1a-f154-485c-b389-feee5c6ed98b
PackageDeployer	Information	8	12-07-2018 01:15:44  Deployment Target Organization UniqueName: org64d361cb
PackageDeployer	Information	8	12-07-2018 01:15:44  Deployment Target Organization Version: 9.0.2.748
PackageDeployer	Information	8	12-07-2018 01:15:44  Deployment Target Organization Uri: https://aaaa.api.crm8.dynamics.com/XRMServices/2011/Organization.svc/web?SDKClientVersion=8.2.0.713
PackageDeployer	Information	8	12-07-2018 01:15:44  Deployment Target Organization Time marker: 07-12-2018 01:15:44 +05:30
PackageDeployer	Information	8	12-07-2018 01:15:44  Completed Config Reading process
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	12-07-2018 01:15:44  Executed Command - RetrieveMultiple : GetEntityDataBySearchParms : duration: 00:00:00.2310703
PackageDeployer	Information	8	12-07-2018 01:15:44  Executing OverrideSolutionImportDecision Custom code
PackageDeployer	Information	8	12-07-2018 01:15:44  Processing Solution RichTextBoxControl(RichTextBoxControl) - Inbound version: 1.0.39.0 - Deployed Version 1.0.39.0, System Determined Import Action: SkipSameVersion
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	12-07-2018 01:15:45  Failed to Execute Command - RetrieveMultiple
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	12-07-2018 01:15:45  Source	: mscorlib
Method	: HandleReturnMessage
Date	: 12-07-2018
Time	: 01:15:45
Error	: Message: Condition for attribute 'solution.uniquename': null is not a valid value for an attribute. Use 'Null' or 'NotNull' conditions instead.
ErrorCode: -2147220989
Trace: 
Stack Trace	: Server stack trace: 
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Xrm.Sdk.IOrganizationService.Execute(OrganizationRequest request)
   at Microsoft.Xrm.Sdk.WebServiceClient.WebProxyClient`1.ExecuteAction[TResult](Func`1 action)
   at Microsoft.Xrm.Tooling.Connector.CrmServiceClient.CrmCommand_Execute(OrganizationRequest req, String errorStringCheck)
======================================================================================================================
Inner Exception Level 1	: 
==OrganizationServiceFault Info=======================================================================================
Error	: Condition for attribute 'solution.uniquename': null is not a valid value for an attribute. Use 'Null' or 'NotNull' conditions instead.
Time	: 11-07-2018 19:45:46
ErrorCode	: -2147220989
Date	: 12-07-2018
Time	: 01:15:45
Trace	: Not Provided
======================================================================================================================
Inner Exception Level 2	: 
==OrganizationServiceFault Info=======================================================================================
Error	: System.ArgumentException: Condition for attribute 'solution.uniquename': null is not a valid value for an attribute. Use 'Null' or 'NotNull' conditions instead.
Time	: 11-07-2018 19:45:46
ErrorCode	: -2147220970
Date	: 12-07-2018
Time	: 01:15:45
Trace	: Not Provided
======================================================================================================================

PackageDeployer	Error	2	12-07-2018 01:15:45  Message: Failed to execute DoImportSolutionItem Method
Source	: Microsoft.Xrm.Tooling.PackageDeployment.CrmPackageCore
Method	: DeterminSolutionAction
Date	: 01:15:45
Time	: 12-07-2018
Error	: Object reference not set to an instance of an object.
Stack Trace	: at Microsoft.Xrm.Tooling.PackageDeployment.CrmPackageCore.ImportCode.BaseImportCustomizations.DeterminSolutionAction(Version soltuionPackageVersion, Version IncomingSolution, Version TargetEnviromentSolution)
   at Microsoft.Xrm.Tooling.PackageDeployment.CrmPackageCore.ImportCode.BaseImportCustomizations.IsSolutionAlreadyDeployed(ConfigSolutionFile Sol)
   at Microsoft.Xrm.Tooling.PackageDeployment.CrmPackageCore.ImportCode.BaseImportCustomizations.DoImportSolutionItem(Object o)
======================================================================================================================


```

Thanks,
Pranav

**Comment by carltoncolter** [comment]
Please try downloading the release and try it again.  It was missing the solution file.  When the solution package builds it creates that zip file, and it looks like I left it out of the PkgFolder in the release zip.  I put it in there and that should solve the issue.

**Comment by blueelvis** [comment]
@carltoncolter - Thanks for the new release. I tried the new one with both Package Deployer and importing the solution manually in Dynamics 365 instance but both are failing.

The log file which is coming from Dynamics 365 is as below. There seems to be some issue with the Request Department Approval Process  - http://pasted.co/e5471add

For PowerShell import, following is the log -
```
PackageDeployer	Information	8	12-07-2018 15:15:12  ************** Solution IMPORT *****************
PackageDeployer	Information	8	12-07-2018 15:15:12  Starting Processing Of Solution: FedBizApps.RequestManagement(FedBizApps_RequestManagement), Version: 0.1.0.60, PackageVersion: 9.0
PackageDeployer	Information	8	12-07-2018 15:15:12  FedBizApps_RequestManagement : User Code Execution : OP=OverrideSolutionImportDecision : Status=Execute
PackageDeployer	Information	8	12-07-2018 15:15:12  FedBizApps_RequestManagement : User Code Execution : OP=OverrideSolutionImportDecision : Status=Complete : Duration=00:00:00.0017879
PackageDeployer	Information	8	12-07-2018 15:15:12  FedBizApps_RequestManagement - Processing Solution - Inbound version: 0.1.0.60 - Deployed Version 0.0.0.0, System Determined Import Action: Import
PackageDeployer	Information	8	12-07-2018 15:15:12  FedBizApps_RequestManagement - ImportSolution - Initial solution install of version 0.1.0.60
PackageDeployer	Information	8	12-07-2018 15:15:12  FedBizApps_RequestManagement - Importing solution for FedBizApps_RequestManagement Version: 0.1.0.60
PackageDeployer	Information	8	12-07-2018 15:15:12  User Code Execution : OP=PreSolutionImport : Status=Execute
PackageDeployer	Information	8	12-07-2018 15:15:12  User Code Execution : OP=PreSolutionImport : Status=Complete : Duration=00:00:00.0012981
PackageDeployer	Information	8	12-07-2018 15:15:12  ImportSolution - Async Supported = True
PackageDeployer	Information	8	12-07-2018 15:15:12  DeleteAndPromote - Async Supported = True
PackageDeployer	Information	8	12-07-2018 15:15:12  FedBizApps_RequestManagement - Executing Solution Import - NormalSolutionLoad 
PackageDeployer	Error	2	12-07-2018 15:16:28  Message: FedBizApps_RequestManagement - Importing solution threw and unforeseen exception
Source	: mscorlib
Method	: HandleReturnMessage
Date	: 15:16:28
Time	: 12-07-2018
Error	: Error while importing workflow {7ada21a6-a83d-466d-a1ef-d070c131a611} type Workflow name Request Department Approval
Stack Trace	: Server stack trace: 
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at Microsoft.Xrm.Tooling.PackageDeployment.CrmPackageCore.ImportCode.BaseImportCustomizations.ExecuteImportSolution(ConfigSolutionFile Sol, String sSolutionImportFilePath)
======================================================================================================================

PackageDeployer	Information	8	12-07-2018 15:16:28  ****** PACKAGE DEPLOYMENT PROCESS COMPLETED. Result:FAILED  Duration:00:01:20.6967013 ******
PackageDeployer	Information	8	12-07-2018 15:16:28  Completed Processing Of Solution: FedBizApps.RequestManagement(FedBizApps_RequestManagement), Version: 0.1.0.60, PackageVersion: 9.0 , Duration: 00:01:16.3870859
```

I checked the XAML file for the given line numbers and they seem to be fine.

Any idea what would be going wrong?

--------------------------------------------------
Also, when you say, `solution package`, you mean the `SolutionPackager.exe` which comes with the Nuget packages right?


Thanks!

**Comment by blueelvis** [comment]
@carltoncolter - I was finally able to repack the solution. There are a few issues though which I noticed as below -

1. The Web Resources are not copied properly. In the `SolutionPackage\package\WebResources\fdbzap_` folder, folders are created but they are empty and only 2 files are copied - `Sample.html.data.xml` & `Sample.html.js.data.xml`
2. The step to include PluginAssemblies fails with the Solution Packager since there are name differences in the plugin assemblies. The name should be `FedBizApps.RequestManagement.Plugins` instead of `FedBizAppsRequestManagementPlugins` (notice the missing period). I edited the name of the folder and the XML inside to reflect that. I also changed the value inside the XML file to reflect this.

After that, the solution was packaged correctly, there were size differences to the one which you provided and one which got packaged over here. Attached it for you.
[FedBizApps_RequestManagement.zip](https://github.com/carltoncolter/dyn-req-mgmt/files/2188278/FedBizApps_RequestManagement.zip)

Replacing the package which you provided with this one got the deployment working and the solution was deployed successfully!

**Comment by carltoncolter** [comment]
@blueelvis I apologize for this taking me so long to resolve.  It took me a while to figure out that somehow my spkl.json files were the default files and not the ones that go with the solution.

The folder errors and plugin name issues are because it uses spkl to package the solution.  Spkl creates a map using the spkl.json files.  The spkl.json files were default files and not the spkl files that go with the solution.  I just committed an update that corrects that.  Now, if you run spkl\pack it will rebuild the solution file correctly.

The problem wasn't that it was just missing the plugin assembly in the solution, because it was missing most of the web resources too, because the packaging uses a map to allow the web resources to live in a different folder, which makes the overall solution easier to manage.

To manually package the SolutionPackage projecct inside the solution without using spkl, you can run the following, with %SolutionPackage% being the path to the SolutionPackage folder in the code.
`
SolutionPackager.exe /action:Pack /zipfile:"FedBizApps_RequestManagement.zip" /folder:"%SolutionPackage%\package" /packagetype:unmanaged /errorlevel:Verbose /nologo /log:packagerlog.txt /map:%SolutionPackage%\map.xml
`

Before uploading it to github, I packaged the solution using spkl, which threw an error that I didn't catch.  Somehow I reset my spkl.json files at some point, which broke the solution packaging.  Now that I have the spkl.json files corrected, you can use **spkl\pack** to build the solution or use the solution packager tool using the syntax above.  The map.xml in the SolutionPackage folder handles the naming difference for the plugin, and maps the webresources for download.

**Comment by blueelvis** [comment]
@carltoncolter - No worries. I forgot to mention earlier but I copied the web resources to the folders and renamed the plugin manually and then ran the Solution Packager which packed the files properly. 

After that, deployment went perfect. Thanks a lot for fixing this as well!
